# BASE IMAGE 
FROM node

# WORKDIR IN CONTAINER
WORKDIR /app/controller

# OPTIMISE BY COPYING PACKAGE.JSON FIRST
# CHECKS FOR DIFFERENCE IN PACKAGE.JSON BEFORE RUNNING NPM INSTALL 
COPY controller/package.json ./

# INSTALL DEPENDENCIES FROM PACKAGE.JSON
RUN npm install

# COPY ALL SOURCE FILES INTO WORKDIR
COPY . /app

# EXPOSE PORT FROM LOCAL TO CONTAINER
EXPOSE 8080

# RUN NODE SERVER/INDEX.JS 
CMD ["node", "controller/server/index.js"]