networks:
  tms: 
    driver: bridge
    
services:
  client:
    container_name: client
    build: ./client
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/var/client
    networks:
      - tms
      
  # controller:
  #   container_name: controller
  #   build: ./controller
  #   ports:
  #     - 3001:3001
    
    
