version: "3.8"
services:
  docker:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4002:8080"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: nodelogin
    links:
      - db
    volumes:
      - ./:/src

  db:
    container_name: mysqldocker
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    volumes:
      - db:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=nodelogin
volumes:
  db:
    driver: local
