version: "3.8"
services:
  backend:
    container_name: backend-container
    image: tms-backend:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    restart: always

    environment:
      NODE_ENV: production
      API_PORT: 4000
      SERVER_HOST: host.docker.internal
      SERVER_USER: root
      SERVER_PASSWORD: admin123
      SERVER_DATABASE: nodelogin

      # MAILTRAP ENV
      MAILTRAP_HOST: smtp.mailtrap.io
      MAILTRAP_PORT: 2525
      MAILTRAP_USER: cb54ffdc01d3d4
      MAILTRAP_PASS: 998e56d9d549da

    volumes:
      - ./:/src
        # - ./controller:/app
        # - /app/controller

    # depends_on:
    #   - db
    # links:
    #   - db

    networks:
      - tms-network

  # frontend:
  #   container_name: frontend-container
  #   image: tms-frontend:latest
  #   build:
  #     context: .
  #     dockerfile: ../client/Dockerfile
  #   ports:
  #     - "3000:3000"
  #   restart: always
  #   networks:
  #     - tms-network
#   db:
#     container_name: mysql-container
#     image: mysql:5.7
#     ports:
#       - "3307:3306"
#     restart: always

#     environment:
#       # ROOT USER PASSWORD
#       MYSQL_ROOT_PASSWORD: admin123
#       MYSQL_DATABASE: nodelogin
#       # MYSQL_USER: admin123
#       # MYSQL_PASSWORD: admin123

#     volumes:
#       # persistent data
#       - mysql-container:/var/lib/mysql
#       # - ./storage

#       # init database schema with sql file
#       - ./server:/docker-entrypoint-initdb.d

#     # networks:
#     #   - container-network

# volumes:
#   mysql-container:
#     driver: local

networks:
  tms-network:
    name: tms-network
    driver: bridge
