version: "3.8"
services:
  api:
    container_name: api-container
    image: tms-api
    # network_mode: host
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      NODE_ENV: production
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: root
      DB_PASSWORD: admin123
      DB_NAME: nodelogin
    links:
      - db
    volumes:
      - ./:/src
    
  db:
    container_name: mysql-container
    image: mysql
    ports:
      - "3307:3306"
    restart: always
    volumes:
    # persistent data
      - mysql-container:/var/lib/mysql
    # init database schema with sql file
      - ./server:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=admin123
      - MYSQL_PASSWORD=admin123
      - MYSQL_DATABASE=nodelogin
volumes:
  mysql-container:
    driver: local


