version: "3.8"
services:
  api:
    container_name: api-container
    image: tms-api:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4001:4001"
    restart: always
    depends_on:
      - db
    links:
      - db

    environment:
      NODE_ENV: production
      API_PORT: 4000
      SERVER_HOST: db
      SERVER_USER: root
      SERVER_PASSWORD: admin123
      SERVER_DATABASE: nodelogin

      # MAILTRAP ENV
      MAILTRAP_HOST: smtp.mailtrap.io
      MAILTRAP_PORT: 2525
      MAILTRAP_USER: cb54ffdc01d3d4
      MAILTRAP_PASS: 998e56d9d549da

    volumes:
      - ./:/src
        # - ./controller:/app
        # - /app/controller

    # networks:
    #   - container-network

  db:
    container_name: mysql-container
    image: mysql:5.7
    ports:
      - "3307:3306"
    restart: always

    environment:
      # ROOT USER PASSWORD
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: nodelogin
      # MYSQL_USER: admin123
      # MYSQL_PASSWORD: admin123

    volumes:
      # persistent data
      - mysql-container:/var/lib/mysql
      # - ./storage

      # init database schema with sql file
      - ./server:/docker-entrypoint-initdb.d

    # networks:
    #   - container-network

volumes:
  mysql-container:
    driver: local

networks:
  default:
    name: container-network
    driver: bridge
